version: '3.4'

services:
    fileprocessordb:
        container_name: fileprocessordb
        restart: always    
        ports:
             - "6379:6379"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    sample-frontend-svc:
        container_name: sample-frontend-svc
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - "CacheSettings:ConnectionString=fileProcessorDb:6379"
           - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:15672"
        depends_on:
            - fileprocessordb
            - rabbitmq
        ports:
            - "8006:80"

    sample-backend-svc:
        container_name: sample-backend-svc
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - "CacheSettings:ConnectionString=fileProcessorDb:6379"
           - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:15672"
        depends_on:
            - fileprocessordb
            - rabbitmq
        expose:
            - "8007"


    ocelotapigw:
        container_name: ocelotapigw
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - sample-frontend-svc
        ports:
            - "8010:80"

    elasticsearch:
        container_name: elasticsearch
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data

    kibana:
        container_name: kibana
        environment:        
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - sample-frontend-svc
        ports:
            - "4000:4000"