version: '3.4'

services:
 fileprocessordb:
    image: redis:alpine

 rabbitmq:
    image: rabbitmq:3-management-alpine

 ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile 

 sample-frontend-svc:
    image: ${DOCKER_REGISTRY-}sample-frontend-svc
    build:
        context: .
        dockerfile: Services/SampleFrontendSvc/Dockerfile

 sample-backend-svc:
    image: ${DOCKER_REGISTRY-}sample-backend-svc
    build:
        context: .
        dockerfile: Services/SampleBackendSvc/Dockerfile

 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

 kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
    elasticsearch-data:


