version: '3.4'

services:
  ocelotapigw:
    image: ocelotapigw:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "OcelotApiGw"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ocelotapigw$
    volumes:
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src\ApiGateways\OcelotApiGw:/app
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src:/src
      - C:\Users\Calvin\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_ocelotapigw$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ocelotapigw$ \"/app/bin/Debug/net5.0/OcelotApiGw.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  sample-backend-svc:
    image: sample-backend-svc:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SampleBackendSvc"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sample-backend-svc$
    volumes:
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src\Services\SampleBackendSvc:/app
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src:/src
      - C:\Users\Calvin\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sample-backend-svc$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sample-backend-svc$ \"/app/bin/Debug/net5.0/SampleBackendSvc.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  sample-frontend-svc:
    image: sample-frontend-svc:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SampleFrontendSvc"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sample-frontend-svc$
    volumes:
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src\Services\SampleFrontendSvc:/app
      - D:\Git\Workspace\dotnet-microservice-boilerplate\src:/src
      - C:\Users\Calvin\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sample-frontend-svc$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sample-frontend-svc$ \"/app/bin/Debug/net5.0/SampleFrontendSvc.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
